name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Set the npm registry
      - run: npm config set registry https://registry.npmjs.org/

      # Install dependencies
      - run: npm install

      # Bump the version in package.json without creating a Git tag
      - name: Bump version
        run: npm version patch --no-git-tag-version

      # Build the package
      - run: npm run build:package

      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
